services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: axum_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: axum_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
